### ISSUE TITLE
setup_env rake task fails if python2 binaries not available

### ISSUE THREAD

**Issue by kmshultz** [DataDog/datadog-sdk-testing#53]
The `setup_env` task fails with the following error if there's no `python2` available:

```
Errno::ENOENT: No such file or directory - /Users/kentshultz/github.com/DataDog/integrations-core/venv/bin/python
```

The offending line in the task is: https://github.com/DataDog/datadog-sdk-testing/blob/master/lib/tasks/sdk.rake#L22.

I'm on macOS Sierra and only had system Python installed. Once I installed python via homebrew (it contains a python2 symlink), `rake setup_env` completed successfully.

**Comment by truthbk** [comment]
I believe this will take care of it: https://github.com/DataDog/datadog-sdk-testing/pull/63
